---
title: "eda"
author: "Rohan Krishnan"
date: "2024-07-25"
output: pdf_document
---
```{r}
#Load libraries
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggcorrplot)
library(ggtext)
library(gt)
library(skimr)
library(flextable)
library(grDevices)
```

# Import Data
```{r}
#Get file paths
temp <- list.files("../data/raw-data/")

#Read in first df then merge all subsequent dfs
df <- read.csv(paste("../data/raw-data/", temp[1], sep = ""))

for(i in temp[c(2:6,8)]){
  path <- paste("../data/raw-data/", i, sep = "")
  dframe <- read.csv(path, header = T)
  df <- merge(x = df, y = dframe, by = "DATE", all.x = TRUE)
}

#Change DATE column to Date type
df$DATE <- as.Date(df$DATE)

#Filter to only include data from 2003 onwards (most data is NA before that)
post2003 <- df %>%
  filter(DATE >= "2003-01-01")

#Look at data
post2003 %>% glimpse() #GDP.x appears to be reported quarterly -- need to impute intermediate values-- pulled from FRED
#Some duplicate variables, I'll use the ones with fewer NA values
#GDP.y has all values, but unsure of source of data

```

# Data cleaning
```{r}
#Look at scatterplot of GDP

#Make data picker
minDate <- as.Date("2003-01-01")
maxDate <- as.Date("2010-12-01")
dateLimit <- c(minDate, maxDate)
post2003 %>%
  ggplot(aes(x=DATE, y=GDP.x)) +
  geom_point(na.rm = T) + 
  xlab("") +
  theme_clean() + 
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  scale_x_date(limit= dateLimit) 

GDP <- post2003$GDP.x

#Impute NA values using trend
imputeGDP <- imputeTS::na_seadec(GDP)
post2003$imputeGDP <- imputeGDP

#Create imputed category
post2003$imputedYN <- as.factor(ifelse(
  is.na(
    ifelse(post2003$GDP.x == post2003$imputeGDP, 0, 1)) == T, 
  1,0))

#Graph GDP and color in imputed data -- looks like it did pretty good!
post2003 %>%
  ggplot(aes(x = DATE, y = imputeGDP, color = imputedYN)) + 
  geom_point(cex = 1, alpha = 0.50) + 
  xlab("") +
  theme_clean() + 
  theme(axis.text.x=element_text(angle=60, hjust=1)) 
  # +scale_x_date(limit= dateLimit)
```

```{r}
#MORTGAGE3OUS seems to be low quality -- remove
post2003$MORTGAGE30US <- NULL

#Unsure about GDP.y's sources-- remove
post2003$GDP.y <- NULL

#interest_rate is a duplicate of FEDFUNDS-- remove
post2003$interest_rate <- NULL

#home_price_index is a duplicate of CSUSHPISA -- remove
post2003$home_price_index <- NULL

#unemployment_rate is a duplicate of UNRATE -- remove
post2003$unemployment_rate <- NULL

#unsure of data quality of house_for_sale_or_sold -- remove
post2003$house_for_sale_or_sold <- NULL

#Create new df and save for data viz
post2003Viz <- post2003
write_csv(post2003Viz, "../data/cleaned/visualizationData.csv")

#Remove GDP.x from post2003 and only leave imputeGDP, remove imputeYN
post2003$GDP.x <- NULL
post2003$imputedYN <- NULL

#Rename columns
post2003 <- post2003 %>% 
  rename(date = DATE,
         urbanCPI = CPIAUCSL,
         fedFunds = FEDFUNDS,
         clcsHPI = CSUSHPISA,
         buildPermits = building_permits,
         constructionPI = const_price_index,
         delRate = delinquency_rate, 
         houseSub = housing_subsidies,
         mortRate = mortgage_rate,
         constructionUn = construction_unit,
         totalHouse = total_houses,
         totalConstSpend = total_const_spending,
         urbanPop = urban_population,
         unemploymentRate = UNRATE,
         )

#NA check -- still some NA values remaining
colSums(is.na(post2003))

#NAs are low enough that I will just remove them
post2003NoNA <- na.omit(post2003)

#Save as modelling data set
write_csv(post2003NoNA, "../data/modelling/modelling.csv")
```


