---
title: "US Housing Price Index Statistical Analysis"
subtitle: "Individual Recreation With Expanded Data Set"
author: "Rohan Krishnan"
date: "2023-12-20"
output: pdf_document
---

# Introduction

As of November 2023, the U.S. housing market is valued at 47 trillion USD (Rosen, 2023). With an average year-over-year growth rate of 5.5%, the U.S. housing market is becoming an increasingly pivotal factor when calculating the overall welfare of the nation's economy (CEIC Data, 2023). On a consumer level, home ownership remains tied to the "American Dream", as working class citizens across the country work towards purchasing, selling, or renting homes. Investors and economists rely on the Housing Price Index (HPI) as a key metric for assessing investment feasibility and for determining national economic forecasts.

The HPI is a comprehensive macroeconomic measure that monitors the price fluctuations of **single-family** homes nationwide. It also serves as an analytical tool for approximating the changes in the rates of mortgage defaults, prepayments, and housing affordability (Liberto, 2023). The Federal Housing Finance Agency compiles this data by reviewing single family housing mortgages purchased or securitized by Fannie Mac or Freddie Mac. My primary goal for this statistical analysis project was to find an economic data set that I could explore to better understand the U.S. economy. 

## Research Question(s)
The main focus of this project is the Housing Price Index (referred to as HPI from this point onwards). The HPI is affected by several macroeconomic factors, including wage data, inflation, crime, etc. Examining the factors that affect the HPI could yield insightful conculsions with real economic, social, and political relevance. 

The central focus of this research project revolves around the question of how the House Price Index (HPI)  is affected by several  macroeconomic factors. Conducting a project that revolves around the idea of the U.S. house price index can provide us with valuable insights into economic, social, and policy considerations. More precisely,  it can sculpt our knowledge on various aspects such as economic significance meaning that housing is a critical component of the economy. Understanding the factors influencing the HPI can shed light on economic trends, market dynamics, and overall marker of real estate. In addition, you can enrich your understanding about macroeconomic stability. That is to say, housing is often connected to broader economic stability and fluctuations in the HPI can have ripple effects on consumer spending, employment, and overall economic performance. It can help in analyzing consumer behavior where it can aid individuals and families make more informed decisions about homeownership, renting, or other house-related choices. In summary, a project aiming at factors affecting the House Price Index (HPI) is relevant and impactful because it addresses economic, social, and policy dimensions with implications for individuals, businesses, policymakers, and researchers. The final result can have practical applications and contribute to a better understanding of the complex dynamics within the real estate market. The main research questions we are trying analyze are:

1.  What variables are most useful in predicting hpi?

    a\. Which machine learning model best predicts hpi given new data?



# Works Cited

Liberto, D. (2023, August 29). Understanding the House price index (HPI) and how it is used. Understanding the House Price Index (HPI) and How It Is Used. <https://www.investopedia.com/terms/h/house-price-index-hpi.asp> 

Rosen, P. (2023, August 11). The US housing market hits a record value of \$47 trillion as the inventory shortage fuels a price boom. Business Insider. <https://markets.businessinsider.com/news/commodities/housing-market-inventory-shortage-home-prices-value-real-estate-property-2023-8.> 