---
title: "kmeans"
author: "Rohan Krishnan"
date: "2024-07-30"
output: html_document
---
# K Means Clustering

## Load libraries
```{r, message = FALSE}
source("../scripts/useful_functions.R")
library(factoextra)
library(cluster)
library(tidyverse)
```

## Load and preprocess data
```{r}
#Load data + preprocess
df <- read.csv("../data/modelling/modelling.csv")
model_df_preprocess(df)

#Scale df
df_scaled <- df %>%
  select(-clcsHPI, -year, -month) %>%
  scale()
```

## K Means

### Look at silhouette scores, gap statistics, and elbow plot for k means
```{r}
#Visualize silhouette scores -- 6
fviz_nbclust(df_scaled, kmeans, method = "silhouette",
             linecolor = palette[2])+
  labs(title = "Silhouette Scores") +
  theme_bw() + 
  scale_color_manual(values = palette[1]) +
  theme(plot.title = element_text(face = "bold"))

#Visualize gap stat -- 8
fviz_nbclust(df_scaled, kmeans, method = "gap_stat",
             verbose = FALSE, linecolor = palette[2]) +
  labs(title = "Gap Statistic") + 
  theme_bw() + 
  theme(plot.title = element_text(face = "bold"))

#Visualize elbow plot -- 3 or 5?
fviz_nbclust(df_scaled, kmeans, method = "wss",
             linecolor = palette[2]) + 
  labs(title = "Elbow Plot") + 
  theme_bw() + 
  theme(plot.title = element_text(face = "bold"))
```

### Run K Means
```{r}
#Fit K Means -- use silhouette score since metrics don't agree
model_kmeans <- kmeans(df_scaled, centers = 6)
print(model_kmeans)
```

### Visualize clustering
```{r}
#Plot clusters
fviz_cluster(model_kmeans, df_scaled, stand = FALSE, main = "Kmeans Clustering",
             labelsize = 0) +
  scale_color_manual("Cluster", values = year_palette[c(1, 5, 9, 14, 17, 21)]) + 
  scale_fill_manual("Cluster", values = year_palette[c(1, 5, 9, 14, 17, 21)]) +
  scale_shape_manual('Cluster', values=c(19, 20, 21, 22, 23, 24)) + 
  theme_bw() + 
  theme(plot.title = element_text(face = "bold"))

#Look at median hpi across clusters
df_kmeans<-cbind(df, cluster=model_kmeans$cluster)
df_kmeans$cluster <-as.factor(df_kmeans$cluster)

#Plot hpi boxplots separated by cluster
df_kmeans %>%
  ggplot(aes(x=cluster,y=clcsHPI, color = cluster))+
  geom_boxplot() + 
  labs(title="U.S. HPI By Cluster") + 
  scale_color_manual(values = year_palette[c(1, 5, 9, 14, 17, 21)]) + 
  theme_bw() + 
  theme(plot.title = element_text(face = "bold"))
```

